const test = require('tape')
const hid = require('.')

test('fail', function (assert) {
  assert.throws(() => hid.enumerate(''))
  assert.throws(() => hid.enumerate('', 0))
  assert.throws(() => hid.enumerate(0, ''))
  const devices = hid.enumerate()
  assert.ok(devices)
  assert.ok(hid.enumerate(0, 0))

  assert.throws(() => hid.open())
  assert.throws(() => hid.open(''))
  assert.throws(() => hid.open('', 0))
  assert.throws(() => hid.open(0, ''))
  assert.throws(() => hid.open(0, '', 0))
  assert.throws(() => hid.open('', 0, 0))
  assert.throws(() => hid.open(0, 0, 0))
  assert.ok(hid.open(devices[0].vendor_id, devices[0].product_id, devices[0].serial_number))
  const device = hid.open(devices[1].vendor_id, devices[1].product_id)
  assert.ok(device)
  assert.throws(() => hid.write())
  assert.throws(() => hid.write(null))
  assert.throws(() => hid.write(null, Buffer.alloc(0)))
  assert.throws(() => hid.write(device))
  assert.ok(hid.write(device, Buffer.alloc(0)) === 0)

  assert.end()
})
